Repository DoYous/Senials-Backend, pull requests merged in 2024-12, with the labels that each got.

#32 [feature/backend-21/hobbyboard/get-all-hobby] 취미게시판 취미 전체 조회 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/common/mapper/HobbyMapper.java
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/dto/HobbyDTO.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
Labels: ⚡Feature

#50 [feature/backend-23/hobbyboard/get-category-hobby] 취미 게시판 카테고리 기준 취미조회 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/repository/HobbyRepository.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
Labels: ⚡Feature

#52 [feature/backend-5/partyboards/delete-partyboard] 모임 글 삭제 REST API 구현
  http/partyboard.http
  src/main/java/com/senials/partyboard/controller/PartyBoardController.java
  src/main/java/com/senials/partyboard/service/PartyBoardService.java
Labels: ⚡Feature

#53 [feature/backend-24/hobbyreview/get-hobbyreview-all] 취미에 해당하는 후기 전체 조회 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/common/mapper/HobbyReviewMapper.java
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
  src/main/java/com/senials/hobbyreview/dto/HobbyReviewDTO.java
  src/main/java/com/senials/hobbyreview/repository/HobbyReviewRepository.java
  src/main/java/com/senials/hobbyreview/service/HobbyReviewService.java
Labels: ⚡Feature

#54 [feature/backend-33/users/get-user] 회원별 조회 Rest api 기능 구현
  http/user.http
  src/main/java/com/senials/common/mapper/UserMapper.java
  src/main/java/com/senials/example/controller/.gitkeep
  src/main/java/com/senials/example/controller/UserController.java
  src/main/java/com/senials/example/dto/.gitkeep
  src/main/java/com/senials/example/dto/UserDTO.java
  src/main/java/com/senials/example/service/.gitkeep
  src/main/java/com/senials/example/service/UserService.java
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/dto/UserCommonDTO.java
  src/main/java/com/senials/user/dto/UserDTO.java
  src/main/java/com/senials/user/repository/UserRepository.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#55 [feature/backend-34/users/delete-user] 회원별 탈퇴 Rest api 기능 구현
  http/user.http
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#56 [feature/backend-35/users/get-user-all] 모든 회원 조회 Rest api 기능 구현
  http/user.http
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#57 [feature/backend-25/hobbyreview/get-hobbyreview-detail] 취미 게시판 특정 취미 후기 정보 조회 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/hobbyreview/controller/HobbyReviewController.java
  src/main/java/com/senials/hobbyreview/service/HobbyReviewService.java
Labels: ⚡Feature

#58 [feature/backend-3/partyboards/get-partyboard-detail] 모임 상세 조회 REST API 구현
  http/partyboard.http
  src/main/java/com/senials/common/mapper/PartyBoardMapper.java
  src/main/java/com/senials/favorites/repository/FavoritesRepository.java
  src/main/java/com/senials/partyboard/controller/PartyBoardController.java
  src/main/java/com/senials/partyboard/repository/PartyBoardRepository.java
  src/main/java/com/senials/partyboard/service/PartyBoardService.java
Labels: ⚡Feature

#61 [feature/backend-37/users/get-user-calender] 회원별 모임 일정 조회 Rest api 기능 구현
  src/main/java/com/senials/meet/MeetDTO/MeetDTO.java
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/repository/MeetRepository.java
  src/main/java/com/senials/meet/service/MeetService.java
Labels: ⚡Feature

#62 [feature/backend-7/meets/get-all-meets] 모임 내 일정 전체 조회 REST API 구현
  http/meet.http
  src/main/java/com/senials/common/mapper/MeetMapper.java
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/dto/MeetDTO.java
  src/main/java/com/senials/meet/repository/MeetRepository.java
  src/main/java/com/senials/meet/service/MeetService.java
Labels: ⚡Feature

#65 [bugfix/backend-64/duplicated-meets] Meet 도메인 내 중복 오류 수정
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/service/MeetService.java
Labels: ⚡Feature, 🚨Bug

#66 [feature/backend-38/users/get-user-like] 회원별 좋아요한 모임 조회 Rest api 기능 구현
  src/main/java/com/senials/likes/controller/LikesController.java
  src/main/java/com/senials/likes/repository/LikeRepository.java
  src/main/java/com/senials/likes/service/LikesService.java
  src/main/java/com/senials/partyboard/dto/PartyBoardDTO.java
  src/main/java/com/senials/partyboard/dto/PartyBoardDTOForCard.java
Labels: ⚡Feature

#67 [feature/backend-8/meets/register-meet] 모임 일정 추가 REST API 구현
  http/meet.http
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/entity/Meet.java
  src/main/java/com/senials/meet/service/MeetService.java
Labels: ⚡Feature

#68 [feature/backend-27/hobbyreview/delete-hobbyreview] 취미 게시판 취미 후기 삭제 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/hobbyreview/controller/HobbyReviewController.java
  src/main/java/com/senials/hobbyreview/service/HobbyReviewService.java
Labels: ⚡Feature

#70 [feature/backend-9/meets/update-meet] 모임 일정 수정 REST API 구현
  http/meet.http
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/entity/Meet.java
  src/main/java/com/senials/meet/service/MeetService.java
Labels: ⚡Feature

#71 [feature/backend-10/meets/delete-meet] 모임 일정 삭제 REST API 구현
  http/meet.http
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/service/MeetService.java
Labels: ⚡Feature

#72 [feature/backend-40/users/get-user-made] 회원별 생성 모임 조회 Rest api 기능 구현
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#74 [feature/backend-41/users/get-user-favorites] 회원별 관심사 조회 Rest api 기능 구현
  src/main/java/com/senials/favorites/controller/FavoritesController.java
  src/main/java/com/senials/favorites/dto/AddFavoriteDTO.java
  src/main/java/com/senials/favorites/dto/FavoriteSelectDTO.java
  src/main/java/com/senials/favorites/dto/FavoriteTitleDTO.java
  src/main/java/com/senials/favorites/dto/UpdateFavoriteDTO.java
  src/main/java/com/senials/favorites/repository/FavoritesRepository.java
  src/main/java/com/senials/favorites/service/FavoritesService.java
Labels: ⚡Feature

#75 [feature/backend-11/meetmembers/get-all-meetmembers] 모임 일정 참여멤버 조회 REST API 구현
  http/meet.http
  src/main/java/com/senials/common/mapper/UserMapper.java
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meetmember/controller/MeetMemberController.java
  src/main/java/com/senials/meetmember/repository/MeetMemberRepository.java
  src/main/java/com/senials/meetmember/service/MeetMemberService.java
  src/main/java/com/senials/user/dto/UserDTOForPublic.java
Labels: ⚡Feature

#77 [feature/backend-29/suggesthobby/get-suggesthobby-detail] 맞춤형 취미 추천 결과 조회 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/repository/HobbyRepository.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
Labels: ⚡Feature

#79 [feature/backend-14/partyreviews/get-all-partyreviews] 모임 후기 전체 조회 REST API 구현
  http/partyreview.http
  src/main/java/com/senials/common/mapper/PartyReviewMapper.java
  src/main/java/com/senials/partyreview/controller/PartyReviewController.java
  src/main/java/com/senials/partyreview/dto/PartyReviewDTO.java
  src/main/java/com/senials/partyreview/entity/PartyReview.java
  src/main/java/com/senials/partyreview/repository/PartyReviewRepository.java
  src/main/java/com/senials/partyreview/service/PartyReviewService.java
Labels: ⚡Feature

#78 [feature/backend-43/users/post-user-favorites] 회원별 관심사 추가 Rest api 기능 구현
  http/favorites.http
  src/main/java/com/senials/favorites/controller/FavoritesController.java
  src/main/java/com/senials/favorites/entity/Favorites.java
  src/main/java/com/senials/favorites/service/FavoritesService.java
Labels: ⚡Feature

#80 [feature/backend-15/partyreviews/register-partyreview] 모임 후기 작성 REST API 구현
  http/partyreview.http
  src/main/java/com/senials/partyreview/controller/PartyReviewController.java
  src/main/java/com/senials/partyreview/entity/PartyReview.java
  src/main/java/com/senials/partyreview/service/PartyReviewService.java
Labels: ⚡Feature

#81 [feature/backend-44/users/post-user-favorites-modify] 회원별 관심사 수정 Rest api 기능 구현
  http/favorites.http
  src/main/java/com/senials/favorites/controller/FavoritesController.java
  src/main/java/com/senials/favorites/service/FavoritesService.java
Labels: ⚡Feature

#82 [feature/backend-16/partyreviews/update-partyreview] 모임 후기 수정 REST API 구현
  http/partyreview.http
  src/main/java/com/senials/partyreview/controller/PartyReviewController.java
  src/main/java/com/senials/partyreview/entity/PartyReview.java
  src/main/java/com/senials/partyreview/service/PartyReviewService.java
Labels: ⚡Feature

#83 [feature/backend-46/users/delete-user-favorites-modify] 회원별 관심사 삭제 Rest api 기능 구현
  http/favorites.http
  src/main/java/com/senials/favorites/controller/FavoritesController.java
  src/main/java/com/senials/favorites/service/FavoritesService.java
Labels: ⚡Feature

#85 [feature/backend-17/partyreviews/delete-partyreview] 모임 후기 삭제 REST API 구현
  http/partyreview.http
  src/main/java/com/senials/partyreview/controller/PartyReviewController.java
  src/main/java/com/senials/partyreview/service/PartyReviewService.java
Labels: ⚡Feature

#84 [feature/backend-30/suggesthobby/post-suggesthobby-result] 맞춤형 취미 추천 나의 취미 등록 Rest api 기능 구현
  http/hobbyTest.http
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
Labels: ⚡Feature

#90 [feature/backend-49/users/pagenation] 사용자별 좋아요한 모임, 만든 모임, 참여한 모임 pagenation 기능 추가
  src/main/java/com/senials/likes/controller/LikesController.java
  src/main/java/com/senials/likes/repository/LikeRepository.java
  src/main/java/com/senials/likes/service/LikesService.java
  src/main/java/com/senials/partyboard/repository/PartyBoardRepository.java
  src/main/java/com/senials/partymember/repository/PartyMemberRepository.java
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#91 [feature/backend-60/users/put-user-profileImg] 사용자 프로필 이미지 수정 기능 추가
  http/user.http
  src/main/java/com/senials/partymember/repository/PartyMemberRepository.java
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/entity/User.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#92 [feature/backend-47/users/get-user-party-count] 사용자 별 모임 개수 조회 Rest api 기능 추가
  http/user.http
  src/main/java/com/senials/likes/controller/LikesController.java
  src/main/java/com/senials/likes/repository/LikeRepository.java
  src/main/java/com/senials/likes/service/LikesService.java
  src/main/java/com/senials/partyboard/repository/PartyBoardRepository.java
  src/main/java/com/senials/partymember/repository/PartyMemberRepository.java
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/service/UserService.java
Labels: ⚡Feature

#93 [feature/backend-12/meetmembers/join-meet] 모임 일정 참여 REST API 구현
  http/meetmember.http
  src/main/java/com/senials/meet/repository/MeetRepository.java
  src/main/java/com/senials/meetmember/controller/MeetMemberController.java
  src/main/java/com/senials/meetmember/repository/MeetMemberRepository.java
  src/main/java/com/senials/meetmember/service/MeetMemberService.java
Labels: ⚡Feature

#139 [feature/backend-138/partyboards/develop-image-modify] 모임 대표 이미지 저장 로직 개선
  http/category.http
  http/partyboard.http
  src/main/java/com/senials/partyboard/controller/PartyBoardController.java
  src/main/java/com/senials/partyboard/dto/PartyBoardDTOForDetail.java
  src/main/java/com/senials/partyboard/dto/PartyBoardDTOForModify.java
  src/main/java/com/senials/partyboard/entity/PartyBoard.java
  src/main/java/com/senials/partyboard/service/PartyBoardService.java
  src/main/java/com/senials/partyboardimage/controller/PartyBoardImageController.java
  src/main/resources/static/img/party_board/24/thumbnail/fab32fb74f954f52b989e5f1110a67ee.png
Labels: ⚡Feature, 💪Enhancement

#143 [feature/backend-141/mainpage] 메인페이지 요구 REST API
  http/category.http
  http/hobbyTest.http
  http/meet.http
  src/main/java/com/senials/category/controller/CategoryController.java
  src/main/java/com/senials/category/repository/CategoryRepository.java
  src/main/java/com/senials/category/service/CategoryService.java
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/dto/HobbyDTO.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
  src/main/java/com/senials/partyboardimage/controller/PartyBoardImageController.java
Labels: ⚡Feature, 💪Enhancement

#142 [feature/backend-140/header_search_whole/get-hobby-eachsiez4] 검색된 취미, 모임을 각각 4개씩 조회하는 rest api 구현
  http/hobbyTest.http
  http/partyboard.http
  src/main/java/com/senials/common/mapper/HobbyMapper.java
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyboard/dto/HobbyDTOForCard.java
  src/main/java/com/senials/hobbyboard/repository/HobbyRepository.java
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
  src/main/java/com/senials/partyboard/controller/PartyBoardController.java
  src/main/java/com/senials/partyboard/repository/PartyBoardRepository.java
  src/main/java/com/senials/partyboard/service/PartyBoardService.java
  src/main/resources/static/img/hobby_board/10.png
  src/main/resources/static/img/hobby_board/4.png
  src/main/resources/static/img/hobby_board/5.png
  src/main/resources/static/img/hobby_board/7.png
  src/main/resources/static/img/hobby_board/8.png
Labels: ⚡Feature

#146 [feature/backend-129/party/rest-api] 모임 일정 개별 조회, 모임 후기 개별 조회 rest API 기능
  http/partyreview.http
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/repository/MeetRepository.java
  src/main/java/com/senials/meet/service/MeetService.java
  src/main/java/com/senials/partyreview/controller/PartyReviewController.java
  src/main/resources/static/img/user_profile/1.jpg
Labels: ⚡Feature

#149 [feature/backend-148/meetmembers/rest-api] 일정 멤버 목록 REST API 개선
  http/meet.http
  http/meetmember.http
  src/main/java/com/senials/common/mapper/MeetMapper.java
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/dto/MeetDTOForMember.java
  src/main/java/com/senials/meet/service/MeetService.java
  src/main/java/com/senials/meetmember/controller/MeetMemberController.java
  src/main/java/com/senials/meetmember/repository/MeetMemberRepository.java
  src/main/java/com/senials/meetmember/service/MeetMemberService.java
Labels: ⚡Feature, 💪Enhancement

#150 [bugfix/backend-147/ Missing_database_value] 취미 엔티티 항목 누락 수정
  http/hobbyTest.http
  src/main/java/com/senials/hobbyboard/service/HobbyService.java
  src/main/java/com/senials/hobbyreview/dto/HobbyReviewDTO.java
  src/main/java/com/senials/hobbyreview/entity/HobbyReview.java
  src/main/java/com/senials/hobbyreview/service/HobbyReviewService.java
Labels: 💪Enhancement, 🚨Bug

#151 [feature/backend-137/users/Security] 시큐리티 테스트 페이지 #137
  .gitignore
  build.gradle
  http/login.http
  src/main/java/com/senials/config/SpringConfig.java
  src/main/java/com/senials/hobbyboard/controller/HobbyController.java
  src/main/java/com/senials/hobbyreview/controller/HobbyReviewController.java
  src/main/java/com/senials/likes/controller/LikesController.java
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/security/config/Config.java
  src/main/java/com/senials/security/config/JacksonConfig.java
  src/main/java/com/senials/security/config/WebConfig.java
  src/main/java/com/senials/security/controller/Oauth2Controller.java
  src/main/java/com/senials/security/domain/kakao/KakaoUserInfo.java
  src/main/java/com/senials/security/domain/kakao/auth/Oauth2UserInfo.java
  src/main/java/com/senials/security/domain/kakao/auth/PrincipalDetails.java
  src/main/java/com/senials/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/senials/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/senials/security/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/senials/security/repository/SecurityUserRepository.java
  src/main/java/com/senials/user/controller/UserController.java
  src/main/java/com/senials/user/entity/User.java
Labels: ⚡Feature

#154 [feature/backend-153/partyboards/check-token] 모임 관련 도메인 REST API 토큰 검증
  build.gradle
  src/main/java/com/senials/common/TokenParser.java
  src/main/java/com/senials/config/SpringConfig.java
  src/main/java/com/senials/likes/controller/LikesController.java
  src/main/java/com/senials/meet/controller/MeetController.java
  src/main/java/com/senials/meet/service/MeetService.java
  src/main/java/com/senials/meetmember/controller/MeetMemberController.java
  src/main/java/com/senials/meetmember/service/MeetMemberService.java
  src/main/java/com/senials/partyboard/controller/PartyBoardController.java
  src/main/java/com/senials/partyboard/service/PartyBoardService.java
  src/main/java/com/senials/partymember/controller/PartyMemberController.java
  src/main/java/com/senials/partymember/service/PartyMemberService.java
  src/main/resources/static/img/party_board/26/thumbnail/4d72076829564b508d6c679655aface8.png
Labels: ⚡Feature, 💪Enhancement

#160 #157 #158 신고, 건의 엔티티 생성 / 버그 수정
  src/main/java/com/senials/report/entity/Report.java
  src/main/java/com/senials/suggestion/entity/Suggestion.java
  src/main/java/com/senials/user/controller/UserController.java
  src/main/resources/static/img/party_board/20/thumbnail/028bea3bceaa47aea73f6244a154e102.png
  src/main/resources/static/img/party_board/20/thumbnail/8e9c474c45ad4e91a30b6125030af4b2.png
  src/main/resources/static/img/party_board/20/thumbnail/a0a00687dcc2406dac9afa95e7f04d75.png
  src/main/resources/static/img/party_board/27/thumbnail/0e544ba561ac495a8860fa1bda09ef2e.jpeg
  src/main/resources/static/img/party_board/27/thumbnail/159a2818259d4d9b88fa70f5da17ec2f.jpg
  src/main/resources/static/img/party_board/27/thumbnail/bbc260082e694280a87f9c13fa9a7351.jpg
  src/main/resources/static/img/party_board/28/thumbnail/0057d483fc9b429787c21b07365626ba.png
  src/main/resources/static/img/party_board/28/thumbnail/81151b66a0e54fef80a5bcf5faba0bd8.jpg
Labels: ⚡Feature, 🚨Bug

#162 [feature/backend-161/reports/reporting-api] 신고 REST API 구현
  http/hobbyTest.http
  http/partyreview.http
  src/main/java/com/senials/common/mapper/ReportMapper.java
  src/main/java/com/senials/hobbyreview/controller/HobbyReviewController.java
  src/main/java/com/senials/hobbyreview/service/HobbyReviewService.java
  src/main/java/com/senials/partyreview/controller/PartyReviewController.java
  src/main/java/com/senials/partyreview/service/PartyReviewService.java
  src/main/java/com/senials/report/controller/ReportController.java
  src/main/java/com/senials/report/dto/ReportDTO.java
  src/main/java/com/senials/report/entity/Report.java
  src/main/java/com/senials/report/repository/ReportRepository.java
  src/main/java/com/senials/report/service/ReportService.java
  src/main/java/com/senials/user/controller/UserController.java
Labels: ⚡Feature, 💪Enhancement

#171 [bugfix/backend-170/mysql-kimsangik-fault] nativeQuery 대문자 테이블명 인식 불가
  src/main/java/com/senials/partyboard/repository/PartyBoardRepository.java
  src/main/java/com/senials/partymember/repository/PartyMemberRepository.java
  src/main/java/com/senials/partyreview/repository/PartyReviewRepository.java
Labels: 💪Enhancement, 🚨Bug

#174 [bugfix/backend-173/hobbyboard/modify_hobby_entity] 취미 엔티티 비용 누락 수정.
  src/main/java/com/senials/hobbyreview/entity/HobbyReview.java
  src/main/resources/static/img/hobby_board/11.png
  src/main/resources/static/img/hobby_board/12.png
  src/main/resources/static/img/hobby_board/13.png
  src/main/resources/static/img/hobby_board/14.png
  src/main/resources/static/img/hobby_board/15.png
  src/main/resources/static/img/hobby_board/16.png
  src/main/resources/static/img/hobby_board/17.png
  src/main/resources/static/img/hobby_board/18.png
  src/main/resources/static/img/hobby_board/19.png
  src/main/resources/static/img/hobby_board/20.png
  src/main/resources/static/img/hobby_board/21.png
  src/main/resources/static/img/hobby_board/22.png
  src/main/resources/static/img/hobby_board/23.png
  src/main/resources/static/img/party_board/2/thumbnail/3e89b0dfc0f144ecb7cc7ddb8f04c423.jpg
  src/main/resources/static/img/party_board/6/thumbnail/88fb8e83eccb4e4597e1d84cfa138f28.jpg
  src/main/resources/static/img/user_profile/1.jpg
Labels: ⚡Feature, 🚨Bug
